### ISSUE TITLE
Incompatible with Sodium 0.5.1

### ISSUE THREAD

**Issue by Slooshie1** [kerudion/chunksfadein#51]
**What is the issue?**
The world renders completely white (aside from dynamic blocks from physics mod) and the game crashes when I disable shaders.

**Conditions to reproduce**
Install Sodium 0.5.1, iris 1.6.7 (version in the logs says 1.6.6 dirty but is the same as 1.6.7), and Chunks Fade In v1.0.1 then join a world with shaders. To crash the game, disable shaders.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes/No*

**Full Minecraft logs**
https://mclo.gs/1BJqZ7N

**Comment by vico93** [comment]
I confirm i'm having issues with Sodium 0.5.1 as well.

Tried opening an issue on Sodium repository (https://github.com/CaffeineMC/sodium-fabric/issues/2007), but pajicadvance told me to open here.

**Comment by kerudion** [comment]
Fixed in [f54dc18](https://github.com/kerudion/chunksfadein/commit/f54dc180d6a52a9c0bfddaca61c348c40452148f)

**Comment by piebaker** [comment]
Appears to be an issue still. Using quilt vs fabric & sodium 0.5.2 however

**Comment by kerudion** [comment]
I tested and Sodium 0.5.2 works. Probably you have a different problem or it's specific to Quilt. Please, open another issue with more details

**Comment by vico93** [comment]
> I also have this issue with the latest download from GitGub and Sodium 0.5.2 (using fabric). Not sure if I'm missing something -
> 
> ![image](https://user-images.githubusercontent.com/33150346/264122085-66217080-8064-4fda-a754-fb733839b69f.png)

i think the latest version works only with Sodium 0.4.x

**Comment by visionlewis** [comment]
Thanks - yeah I actually just spotted that in the title - my bad. However, just tried downgrading to 1.0.2 (which lists Sodium 0.5.1 as compatible) but it crashes on startup. Looking now to see if it's another mod.

**Comment by visionlewis** [comment]
Yep, never mind that's my fault. v1.02 of this mod works fine with 0.5.2 of Sodium. Disregard my above comments.
